source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VeeContactPicker_Example', :exclusive => true do
  pod 'VeeContactPicker', :path => '../'
end

target 'VeeContactPicker_Tests', :exclusive => true do
  pod 'VeeContactPicker', :path => '../'
  pod 'OCMock'
  #pod 'FBSnapshotTestCase'
end
