use_frameworks!
platform :ios, '8.0'

target 'VeeContactPicker_Example' do
  pod 'VeeContactPicker', :path => '../'
end

target 'VeeContactPicker_Tests' do
    inherit! :search_paths
    pod 'VeeContactPicker', :path => '../'
    pod 'OCMock'
end
