source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'VeeContactPicker_Example' do
  pod 'VeeContactPicker', :path => '../'
end

target 'VeeContactPicker_Tests' do
  pod 'VeeContactPicker', :path => '../'
  pod 'OCMock'
  #pod 'FBSnapshotTestCase'
end