//
//  Created by Andrea Cipriani on 14/03/16.
//  Copyright © 2016 Code Atlas SRL. All rights reserved.
//

#import "VeeContactProt.h"
#import <Foundation/Foundation.h>

//When a veeContact doesn't have an image show its initials with a circle. The background color of the circle should always be the same for a contact and it's generated by this class

@interface VeeContactColors : NSObject

- (instancetype)initWithVeeContactsDefaultColorPalette;
- (instancetype)initWithVeeContactsColorPalette:(NSArray<UIColor*>*)colorPalette;

@property (nonatomic, strong) NSArray<UIColor*>* veecontactColorsPalette; //Change it to use your palette

- (UIColor*)colorForVeeContact:(id<VeeContactProt>)veeContact;
//The color will be chosen from the color palette by the djb2 algorithm, that is used to generate an unsigned long hash from a given string with the composite name of the veeContact

@end
